# Resources/config/providers.yml
services:

    wbw.adminbsb.provider.javascript:
        class:  WBW\Bundle\AdminBSBBundle\Provider\JavascriptProvider
        public: true
        tags:
            - { name: "wbw.core.provider.javascript" }
